Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'app/mailers/application_mailer.rb'
    - 'app/models/*'
    - 'app/controllers/api/v1/*'
    - 'config/application.rb'
    - 'test/test_helper.rb'
    - 'db/migrate/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/update'
    - 'bin/setup'

Metrics/BlockLength:
  Exclude:
    - 'spec/*/*'
