Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'test/test_helper.rb'
    - 'db/migrate/*'
    - 'app/models/feature.rb'
    - 'app/controllers/api/v1/features_controller.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/update'
    - 'bin/setup'
